# Generated by Django 5.0.7 on 2024-07-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingInvitationApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestattendence',
            name='id',
        ),
        migrations.AlterField(
            model_name='guestattendence',
            name='cell',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
