# Generated by Django 5.0.7 on 2024-07-28 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingInvitationApp', '0002_remove_guestattendence_id_alter_guestattendence_cell'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestsPlusOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plus_one_name', models.CharField(max_length=50)),
                ('plus_one_surname', models.CharField(max_length=25)),
                ('plus_one_relation', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='guestattendence',
            name='cell',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='guestattendence',
            name='plus_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WeddingInvitationApp.guestsplusone'),
        ),
    ]
